11 
    de.renew.gui.CPNDrawing 352 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4935 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 629 166 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4936 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 627 243 24 21 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4937 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 593 293 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4938 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 667 283 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4939 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 555 304 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4940 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 455 163 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4941 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 258 170 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4942 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 919 159 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4943 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 786 167 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4944 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1580 170 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4945 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 688 327 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4946 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 622 973 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4947 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 693 284 "Hälften" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 36 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4948 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 540 289 "Salz" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -13 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4949 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1602 160 "Zitrone" "SansSerif" 1 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 32 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4950 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 940 157 "Eier" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 22 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4951 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 480 162 "Milch" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 30 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4952 2 639 186 639 243 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4953 2 631 264 609 296 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4954 2 648 264 671 287 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4955 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 655 263 "[];[];" "SansSerif" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 5 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4956 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 563 516 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4957 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 417 523 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4958 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 446 525 "verrühren" "SansSerif" 1 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 45 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4959 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 452 230 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4960 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 710 510 24 17 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4961 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 847 509 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4962 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 594 913 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4963 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 564 1037 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4964 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 622 1148 24 17 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4965 2 465 183 464 230 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 48   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4966 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 493 294 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4967 2 468 246 499 296 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 48  
            CH.ifa.draw.figures.ChopEllipseConnector REF 58   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4968 2 506 314 572 516 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 58  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4969 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 416 297 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4970 2 459 246 431 299 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 48  
            CH.ifa.draw.figures.ChopEllipseConnector REF 67   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4971 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 663 167 "Vanilleschote" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 62 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4972 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 490 228 "trennen" "SansSerif" 1 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4973 2 565 324 574 516 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4974 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 598 516 "aufkochen" "SansSerif" 1 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 53 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4975 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 815 156 "Zucker" "SansSerif" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 39 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4976 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 257 150 "Stärke" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 8 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4977 2 268 190 265 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5049 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 253 233 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4978 2 426 317 428 523 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 67  
            CH.ifa.draw.standard.ChopBoxConnector REF 44   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4979 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 417 276 "Tasse" "SansSerif" 1 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 8 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4980 2 929 179 926 238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4988 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 914 238 24 16 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4981 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 655 1146 "auffüllen" "SansSerif" 1 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 45 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4982 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 631 912 "unterheben" "SansSerif" 1 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 57 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4983 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 746 510 "einrühren" "SansSerif" 1 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 51 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4984 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 576 277 "Mark" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -13 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4985 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 672 239 "aufschneiden" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 71 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4986 2 603 313 576 516 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4987 2 674 302 578 516 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   REF 107 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4989 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 952 236 "trennen" "SansSerif" 1 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4990 2 938 253 1049 319 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 107  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5074 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1047 313 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4991 2 938 249 1172 320 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 107  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5077 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1171 312 20 20 NULL    
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4992 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1581 226 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4993 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1619 224 "trennen" "SansSerif" 1 12 0 REF 144 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4994 2 1591 190 1592 226 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 144   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4995 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1530 283 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4996 2 1585 242 1547 287 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 144  
            CH.ifa.draw.figures.ChopEllipseConnector REF 152   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4997 2 1531 296 734 515 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 152  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4998 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1547 310 "Zitronensaft" "SansSerif" 1 12 0 REF 152 
            CH.ifa.draw.standard.OffsetLocator 41 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4999 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 715 312 "Wein" "SansSerif" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 31 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5000 2 699 347 720 510 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5001 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 558 607 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5002 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 596 605 "trennen" "SansSerif" 1 12 0 REF 171 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5003 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 562 556 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5004 2 574 532 573 557 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 43  
            CH.ifa.draw.figures.ChopEllipseConnector REF 175   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5005 2 572 576 570 607 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 175  
            CH.ifa.draw.standard.ChopBoxConnector REF 171   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5006 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1121 784 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5007 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 516 629 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5008 2 582 618 1122 792 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 171  
            CH.ifa.draw.figures.ChopEllipseConnector REF 184   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5009 2 558 621 535 635 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 171  
            CH.ifa.draw.figures.ChopEllipseConnector REF 185   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5010 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 492 654 "Vanillemilch" "SansSerif" 1 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator 0 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5011 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 429 563 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5012 2 430 539 438 564 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 44  
            CH.ifa.draw.figures.ChopEllipseConnector REF 197   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5013 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 432 721 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5014 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 468 721 "einrühren" "SansSerif" 1 12 0 REF 202 
            CH.ifa.draw.standard.OffsetLocator 51 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5015 2 439 583 443 721 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 197  
            CH.ifa.draw.standard.ChopBoxConnector REF 202   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5016 2 520 646 451 721 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 185  
            CH.ifa.draw.standard.ChopBoxConnector REF 202   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5017 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 450 757 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5018 2 447 737 457 759 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 202  
            CH.ifa.draw.figures.ChopEllipseConnector REF 214   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5019 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 491 794 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5020 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 526 794 "aufkochen" "SansSerif" 1 12 0 REF 219 
            CH.ifa.draw.standard.OffsetLocator 53 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5021 2 468 773 493 794 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 214  
            CH.ifa.draw.standard.ChopBoxConnector REF 219   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5022 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 550 837 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5023 2 513 810 553 842 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 219  
            CH.ifa.draw.figures.ChopEllipseConnector REF 227   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5024 2 565 855 601 913 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 227  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5025 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 652 817 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5026 2 853 525 667 820 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 50  
            CH.ifa.draw.figures.ChopEllipseConnector REF 236   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5027 2 658 836 610 913 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 236  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5028 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 570 975 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5029 3 603 929 596 957 585 977 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.figures.ChopEllipseConnector REF 245   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5030 2 580 995 576 1037 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 245  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5031 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 593 1104 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5032 2 579 1053 600 1106 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector REF 254   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5033 2 609 1122 627 1148 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 254  
            CH.ifa.draw.standard.ChopBoxConnector REF 53   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5034 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 647 1101 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5035 2 721 527 658 1102 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 263   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5036 2 653 1120 638 1148 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 263  
            CH.ifa.draw.standard.ChopBoxConnector REF 53   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5037 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 633 1184 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5038 2 636 1165 642 1185 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 53  
            CH.ifa.draw.figures.ChopEllipseConnector REF 272   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5039 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 882 508 "abschlagen" "SansSerif" 1 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator 56 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5040 2 626 990 583 1037 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5041 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 635 168 "[];" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5042 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 925 161 "[];" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5043 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 561 306 "[];" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5044 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1586 172 "[];" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5045 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 443 263 "[];[];[];[];[];[];[];[];[];" "SansSerif" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5046 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 144 203 "[]@10;[]@10;[]@10;[]@10;[]@10;[]@10;[]@10;" "SansSerif" 0 12 0 REF 91 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5047 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 289 198 "[]@10;[]@10;[]@10;[]@10;[]@10;[]@10;[]@10;[]@10;[]@10;[]@10;" "SansSerif" 0 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5048 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 576 945 "[];[];[];[];" "SansSerif" 0 12 0 REF 246 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 95 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5050 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 291 231 "trennen" "SansSerif" 1 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5051 2 277 248 361 304 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 95  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5052 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 358 299 20 20 NULL    REF 315 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5053 2 371 319 426 523 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 315  
            CH.ifa.draw.standard.ChopBoxConnector REF 44   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5054 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 306 268 "[];[];[];" "SansSerif" 0 12 0 REF 311 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5055 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 196 298 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5056 2 215 312 710 513 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 323  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5057 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 769 238 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5058 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 807 236 "trennen" "SansSerif" 1 12 0 REF 328 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5059 2 795 187 782 238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector REF 328   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5060 2 785 254 815 305 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 328  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5061 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 809 303 20 20 NULL    REF 340 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5062 2 816 322 726 510 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 340  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5063 2 777 254 762 295 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 328  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5064 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 748 293 20 20 NULL    REF 349 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5065 2 753 311 581 516 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 349  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5066 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 736 408 "[]@20;[]@20;" "SansSerif" 0 12 0 REF 341 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5067 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 734 202 "[]@10;[]@10;[]@10;" "SansSerif" 0 12 0 REF 332 
            CH.ifa.draw.standard.OffsetLocator -2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5068 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 800 250 "[];[];" "SansSerif" 0 12 0 REF 336 
            CH.ifa.draw.standard.OffsetLocator 9 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5069 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1138 148 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5070 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1159 146 "Eier" "SansSerif" 1 12 0 REF 363 
            CH.ifa.draw.standard.OffsetLocator 22 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5071 2 1148 168 1148 229 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 363  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5072 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1136 229 24 16 NULL    REF 371 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5073 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1174 227 "trennen" "SansSerif" 1 12 0 REF 371 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 138 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5075 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1081 315 "Eiweiss" "SansSerif" 1 12 0 REF 138 
            CH.ifa.draw.standard.OffsetLocator 46 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5076 2 1139 245 1064 317 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 371  
            CH.ifa.draw.figures.ChopEllipseConnector REF 138   REF 143 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5078 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1163 331 "Eigelb" "SansSerif" 1 12 0 REF 143 
            CH.ifa.draw.standard.OffsetLocator -1 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5079 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1144 150 "[];" "SansSerif" 0 12 0 REF 363 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5080 2 1151 245 1178 314 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 371  
            CH.ifa.draw.figures.ChopEllipseConnector REF 143   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5081 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1373 162 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5082 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1394 160 "Eier" "SansSerif" 1 12 0 REF 392 
            CH.ifa.draw.standard.OffsetLocator 22 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5083 2 1383 182 1382 226 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 392  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5084 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1370 226 24 16 NULL    REF 400 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5085 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1408 224 "trennen" "SansSerif" 1 12 0 REF 400 
            CH.ifa.draw.standard.OffsetLocator 48 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5086 2 1370 237 1067 321 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 400  
            CH.ifa.draw.figures.ChopEllipseConnector REF 138   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5087 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1379 164 "[];" "SansSerif" 0 12 0 REF 392 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5088 2 1370 239 1190 319 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 400  
            CH.ifa.draw.figures.ChopEllipseConnector REF 143   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5089 3 1049 327 909 382 861 509 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 138  
            CH.ifa.draw.standard.ChopBoxConnector REF 50   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5090 2 1173 326 734 513 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 143  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5091 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 612 994 "Gläser" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -2 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5092 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 236 174 "[];[];[];[];[];[];[];" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -1 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5093 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 622 1209 "Welfencreme" "SansSerif" 1 12 0 REF 272 
            CH.ifa.draw.standard.OffsetLocator 17 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5094 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 662 1122 "Weinsoße" "SansSerif" 1 12 0 REF 263 
            CH.ifa.draw.standard.OffsetLocator 33 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5095 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 509 1123 "Gläser mit Creme" "SansSerif" 1 12 0 REF 254 
            CH.ifa.draw.standard.OffsetLocator -45 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5096 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 528 984 "Creme" "SansSerif" 1 12 0 REF 245 
            CH.ifa.draw.standard.OffsetLocator -33 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5097 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 149 325 "Stärke für die Soße" "SansSerif" 1 12 0 REF 323 
            CH.ifa.draw.standard.OffsetLocator -3 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5098 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 307 320 "Stärke für die Creme" "SansSerif" 1 12 0 REF 315 
            CH.ifa.draw.standard.OffsetLocator -2 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5099 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 502 277 "Restmilch" "SansSerif" 1 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 27 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5100 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 695 296 "Zucker für die Creme" "SansSerif" 1 12 0 REF 349 
            CH.ifa.draw.standard.OffsetLocator -3 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5101 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 788 165 "[];[];[];" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 5 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5102 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 417 163 "[];[];[];[];[];[];[];[];[];[];" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -3 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5103 4 257 249 246 262 235 275 213 301 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 95  
            CH.ifa.draw.figures.ChopEllipseConnector REF 323   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5104 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 787 281 "Zucker für die Soße" "SansSerif" 1 12 0 REF 340 
            CH.ifa.draw.standard.OffsetLocator 23 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5105 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 692 327 "[];" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5106 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 678 829 "[];[];[];[];" "SansSerif" 0 12 0 REF 264 
            CH.ifa.draw.standard.OffsetLocator 7 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5107 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 612 974 "[];[];[];[];" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5108 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 391 565 "Verrührte Masse" "SansSerif" 1 12 0 REF 197 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5109 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 586 561 "Aufgekochte Masse" "SansSerif" 1 12 0 REF 175 
            CH.ifa.draw.standard.OffsetLocator 70 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5110 3 1599 242 1685 347 1139 789 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 144  
            CH.ifa.draw.figures.ChopEllipseConnector REF 184   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5111 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1147 792 "Abfall" "SansSerif" 1 12 0 REF 184 
            CH.ifa.draw.standard.OffsetLocator 32 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5112 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 217 267 "[];[];[];[];" "SansSerif" 0 12 0 REF 459 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5113 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 478 755 "Eingerührte Masse" "SansSerif" 1 12 0 REF 214 
            CH.ifa.draw.standard.OffsetLocator 71 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5114 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 675 817 "Abgeschlagene Masse" "SansSerif" 1 12 0 REF 236 
            CH.ifa.draw.standard.OffsetLocator 77 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5115 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 444 854 "Aufgekochte Masse" "SansSerif" 1 12 0 REF 227 
            CH.ifa.draw.standard.OffsetLocator -60 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5116 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 874 377 "[]@20;[]@20;[]@20;" "SansSerif" 0 12 0 REF 415 
            CH.ifa.draw.standard.OffsetLocator -29 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5117 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 901 411 "[]@20;[]@20;[]@20;" "SansSerif" 0 12 0 REF 419 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5118 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 441 264 "[];" "SansSerif" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5119 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 616 272 "[];" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5120 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 622 206 "[]@10;" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5121 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1131 190 "[]@10;" "SansSerif" 0 12 0 REF 367 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5122 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 910 200 "[]@10;" "SansSerif" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5123 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1574 200 "[]@10;" "SansSerif" 0 12 0 REF 148 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5124 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1562 256 "[];" "SansSerif" 0 12 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5125 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1408 507 "[];" "SansSerif" 0 12 0 REF 481 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5126 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1115 397 "[]@20;" "SansSerif" 0 12 0 REF 157 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5127 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1276 271 "[];" "SansSerif" 0 12 0 REF 411 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5128 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1214 271 "[];" "SansSerif" 0 12 0 REF 404 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5129 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1160 271 "[];" "SansSerif" 0 12 0 REF 388 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5130 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1097 273 "[];" "SansSerif" 0 12 0 REF 378 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5131 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1051 276 "[];" "SansSerif" 0 12 0 REF 139 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5132 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 989 278 "[];" "SansSerif" 0 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5133 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 430 543 "[];" "SansSerif" 0 12 0 REF 198 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5134 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 569 536 "[];" "SansSerif" 0 12 0 REF 176 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5135 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 692 420 "[]@20;" "SansSerif" 0 12 0 REF 167 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5136 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 756 664 "[];" "SansSerif" 0 12 0 REF 237 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5137 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 848 697 "[];" "SansSerif" 0 12 0 REF 186 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5138 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 554 583 "[]@15;" "SansSerif" 0 12 0 REF 180 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5139 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 542 620 "[];" "SansSerif" 0 12 0 REF 190 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5140 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 468 675 "[]@25;" "SansSerif" 0 12 0 REF 210 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5141 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 424 644 "[]@25;" "SansSerif" 0 12 0 REF 206 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5142 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 448 740 "[];" "SansSerif" 0 12 0 REF 215 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5143 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 463 775 "[]@17;" "SansSerif" 0 12 0 REF 223 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5144 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 529 818 "[];" "SansSerif" 0 12 0 REF 228 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5145 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 566 876 "[]@32;" "SansSerif" 0 12 0 REF 232 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5146 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 617 866 "[]@32;" "SansSerif" 0 12 0 REF 241 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5147 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 587 1005 "[]@25;" "SansSerif" 0 12 0 REF 280 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5148 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 561 1008 "[]@25;" "SansSerif" 0 12 0 REF 250 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5149 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 601 1127 "[]@12;" "SansSerif" 0 12 0 REF 259 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5150 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 628 1126 "[]@12;" "SansSerif" 0 12 0 REF 268 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5151 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 635 1167 "[];" "SansSerif" 0 12 0 REF 273 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5152 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 585 1071 "[];" "SansSerif" 0 12 0 REF 255 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5153 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1377 190 "[]@10;" "SansSerif" 0 12 0 REF 396 
            CH.ifa.draw.standard.OffsetLocator 12 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5154 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 304 412 "[]@15;[]@15;[]@15;" "SansSerif" 0 12 0 REF 316 
            CH.ifa.draw.standard.OffsetLocator -42 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5155 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 417 438 "[]@15;" "SansSerif" 0 12 0 REF 96 
            CH.ifa.draw.standard.OffsetLocator 7 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5156 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 271 353 "[]@20;[]@20;[]@20;[]@20;[]@20;[]@20;[]@20;[]@20;[]@20;" "SansSerif" 0 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator -111 -54 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5157 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 413 425 "[]@20;[]@20;[]@20;[]@20;" "SansSerif" 0 12 0 REF 324 
            CH.ifa.draw.standard.OffsetLocator 21 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5158 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 617 397 "[]@20;[]@20;" "SansSerif" 0 12 0 REF 127 
            CH.ifa.draw.standard.OffsetLocator 26 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5159 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 547 390 "[]@20;" "SansSerif" 0 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator -5 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5160 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 572 406 "[]@20;" "SansSerif" 0 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5161 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 650 405 "[]@20;" "SansSerif" 0 12 0 REF 350 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5162 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 598 1043 "abfüllen" "SansSerif" 1 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 44 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 5163 "FillColor" "Color" 255 200 0 255 196 592 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5164 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 186 621 "Köche" "SansSerif" 1 12 0 REF 641 
            CH.ifa.draw.standard.OffsetLocator -2 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5165 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 554 111 20 20 NULL REF 641  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5166 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 536 142 "Köche" "SansSerif" 1 12 0 REF 645 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5167 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1253 44 20 20 NULL REF 641  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5168 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1235 75 "Köche" "SansSerif" 1 12 0 REF 649 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5169 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 353 28 20 20 NULL REF 641  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5170 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 335 59 "Köche" "SansSerif" 1 12 0 REF 653 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5171 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 344 475 20 20 NULL REF 641  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5172 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 326 506 "Köche" "SansSerif" 1 12 0 REF 657 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5173 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 834 421 20 20 NULL REF 641  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5174 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 816 452 "Köche" "SansSerif" 1 12 0 REF 661 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5175 2 363 490 417 523 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 657  
            CH.ifa.draw.standard.ChopBoxConnector REF 44   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5176 2 364 487 563 521 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 657  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5177 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 591 668 20 20 NULL REF 641  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5178 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 573 699 "Köche" "SansSerif" 1 12 0 REF 675 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5179 2 573 623 598 670 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 171  
            CH.ifa.draw.figures.ChopEllipseConnector REF 675   
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5180 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 453 1004 20 20 NULL REF 641  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5181 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 435 1035 "Köche" "SansSerif" 1 12 0 REF 684 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5182 2 268 233 360 47 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 95  
            CH.ifa.draw.figures.ChopEllipseConnector REF 653   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5183 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 311 132 "a" "SansSerif" 0 12 0 REF 688 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5184 2 368 47 459 230 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 653  
            CH.ifa.draw.standard.ChopBoxConnector REF 48   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5185 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 410 130 "a" "SansSerif" 0 12 0 REF 696 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5186 2 569 130 633 243 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 645  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5187 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 598 178 "a" "SansSerif" 0 12 0 REF 704 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5188 3 574 122 696 141 774 238 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 645  
            CH.ifa.draw.standard.ChopBoxConnector REF 328   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5189 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 669 133 "a" "SansSerif" 0 12 0 REF 712 
            CH.ifa.draw.standard.OffsetLocator -2 -39 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5190 2 1255 59 938 239 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 649  
            CH.ifa.draw.standard.ChopBoxConnector REF 107   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5191 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1093 141 "a" "SansSerif" 0 12 0 REF 720 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5192 2 1153 229 1259 62 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 371  
            CH.ifa.draw.figures.ChopEllipseConnector REF 649   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5193 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1203 137 "a" "SansSerif" 0 12 0 REF 728 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5194 2 1272 59 1581 227 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 649  
            CH.ifa.draw.standard.ChopBoxConnector REF 144   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5195 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1423 135 "a" "SansSerif" 0 12 0 REF 736 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5196 2 1269 62 1376 226 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 649  
            CH.ifa.draw.standard.ChopBoxConnector REF 400   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5197 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1319 136 "a" "SansSerif" 0 12 0 REF 744 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5198 2 733 510 837 437 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 661   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5199 2 846 441 857 509 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 661  
            CH.ifa.draw.standard.ChopBoxConnector REF 50   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5200 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 782 465 "a" "SansSerif" 0 12 0 REF 752 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5201 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 848 467 "a" "SansSerif" 0 12 0 REF 757 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5202 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 460 496 "a" "SansSerif" 0 12 0 REF 670 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5203 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 387 498 "a" "SansSerif" 0 12 0 REF 665 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5204 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 582 638 "a" "SansSerif" 0 12 0 REF 679 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5205 2 456 725 592 681 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 202  
            CH.ifa.draw.figures.ChopEllipseConnector REF 675   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5206 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 521 695 "a" "SansSerif" 0 12 0 REF 777 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5207 2 509 794 596 686 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 219  
            CH.ifa.draw.figures.ChopEllipseConnector REF 675   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5208 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 549 732 "a" "SansSerif" 0 12 0 REF 785 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5209 2 601 688 605 913 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 675  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5210 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 600 792 "a" "SansSerif" 0 12 0 REF 793 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5211 2 473 1017 564 1041 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 684  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5212 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 515 1021 "a" "SansSerif" 0 12 0 REF 801 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5213 2 471 1020 623 1148 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 684  
            CH.ifa.draw.standard.ChopBoxConnector REF 53   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5214 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 544 1076 "a" "SansSerif" 0 12 0 REF 809 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 5215 "FillColor" "Color" 255 175 175 255 134 779 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5216 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 111 806 "Fähigkeiten" "SansSerif" 1 12 0 REF 817 
            CH.ifa.draw.standard.OffsetLocator -1 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5217 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1150 54 20 20 NULL REF 817  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5218 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1105 83 "Fähigkeiten" "SansSerif" 1 12 0 REF 821 
            CH.ifa.draw.standard.OffsetLocator -23 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5219 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 816 637 20 20 NULL REF 817  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5220 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 771 666 "Fähigkeiten" "SansSerif" 1 12 0 REF 825 
            CH.ifa.draw.standard.OffsetLocator -23 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5221 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 261 26 20 20 NULL REF 817  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5222 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 216 55 "Fähigkeiten" "SansSerif" 1 12 0 REF 829 
            CH.ifa.draw.standard.OffsetLocator -23 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5223 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 714 70 20 20 NULL REF 817  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5224 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 669 99 "Fähigkeiten" "SansSerif" 1 12 0 REF 833 
            CH.ifa.draw.standard.OffsetLocator -23 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5225 2 271 46 265 233 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 829  
            CH.ifa.draw.standard.ChopBoxConnector REF 95   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5226 2 278 43 456 230 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 829  
            CH.ifa.draw.standard.ChopBoxConnector REF 48   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5227 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 265 131 "b" "SansSerif" 0 12 0 REF 837 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5228 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 364 128 "b" "SansSerif" 0 12 0 REF 842 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5229 2 644 243 721 89 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 833   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5230 2 778 238 727 89 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 328  
            CH.ifa.draw.figures.ChopEllipseConnector REF 833   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5231 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 679 158 "b" "SansSerif" 0 12 0 REF 853 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5232 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 749 155 "b" "SansSerif" 0 12 0 REF 858 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5233 2 936 238 1153 70 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 107  
            CH.ifa.draw.figures.ChopEllipseConnector REF 821   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5234 2 1148 229 1160 74 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 371  
            CH.ifa.draw.figures.ChopEllipseConnector REF 821   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5235 2 1371 226 1168 70 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 400  
            CH.ifa.draw.figures.ChopEllipseConnector REF 821   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5236 2 1581 229 1169 68 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 144  
            CH.ifa.draw.figures.ChopEllipseConnector REF 821   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5237 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1041 146 "b" "SansSerif" 0 12 0 REF 869 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5238 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1151 143 "b" "SansSerif" 0 12 0 REF 874 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5239 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1266 140 "b" "SansSerif" 0 12 0 REF 879 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5240 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1372 140 "b" "SansSerif" 0 12 0 REF 884 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5241 2 821 640 728 527 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 825  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5242 2 828 638 856 525 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 825  
            CH.ifa.draw.standard.ChopBoxConnector REF 50   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5243 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 771 575 "b" "SansSerif" 0 12 0 REF 901 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5244 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 839 573 "b" "SansSerif" 0 12 0 REF 906 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5245 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 335 570 20 20 NULL REF 817  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5246 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 290 599 "Fähigkeiten" "SansSerif" 1 12 0 REF 917 
            CH.ifa.draw.standard.OffsetLocator -23 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5247 2 354 576 417 538 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 917  
            CH.ifa.draw.standard.ChopBoxConnector REF 44   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5248 2 355 579 563 526 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 917  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5249 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 382 549 "b" "SansSerif" 0 12 0 REF 921 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5250 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 456 544 "b" "SansSerif" 0 12 0 REF 926 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5251 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 364 853 20 20 NULL REF 817  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5252 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 319 882 "Fähigkeiten" "SansSerif" 1 12 0 REF 937 
            CH.ifa.draw.standard.OffsetLocator -23 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5253 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 798 1058 20 20 NULL REF 817  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5254 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 753 1087 "Fähigkeiten" "SansSerif" 1 12 0 REF 941 
            CH.ifa.draw.standard.OffsetLocator -23 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5255 2 384 865 594 917 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 937  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5256 2 383 860 491 807 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 937  
            CH.ifa.draw.standard.ChopBoxConnector REF 219   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5257 2 379 855 439 737 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 937  
            CH.ifa.draw.standard.ChopBoxConnector REF 202   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5258 2 799 1068 588 1046 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 941  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5259 2 800 1073 646 1150 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 941  
            CH.ifa.draw.standard.ChopBoxConnector REF 53   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5260 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 484 883 " b" "SansSerif" 0 12 0 REF 945 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5261 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 434 825 "b" "SansSerif" 0 12 0 REF 950 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5262 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 406 788 "b" "SansSerif" 0 12 0 REF 955 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5263 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 690 1049 "b" "SansSerif" 0 12 0 REF 960 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5264 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 720 1103 "b" "SansSerif" 0 12 0 REF 965 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5265 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 168 569 "\"K1\";\"K2\";\"K3\";\"K4\";" "SansSerif" 0 12 0 REF 641 
            CH.ifa.draw.standard.OffsetLocator 14 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5267 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 86 234 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator -101 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5282 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 517 913 "guard b.equals([a,\"unterheben\"])" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5280 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 256 694 "guard b.equals([a,\"einrühren\"])" "SansSerif" 0 12 0 REF 202 
            CH.ifa.draw.standard.OffsetLocator -104 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5286 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 536 596 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 171 
            CH.ifa.draw.standard.OffsetLocator 44 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5277 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 479 483 "guard b.equals([a,\"aufkochen\"])" "SansSerif" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator -10 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5287 2 355 582 558 613 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 917  
            CH.ifa.draw.standard.ChopBoxConnector REF 171   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5288 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 453 589 "b" "SansSerif" 0 12 0 REF 1003 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5276 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 243 523 "guard b.equals([a,\"verrühren\"])" "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator -103 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5278 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 643 540 "guard b.equals([a,\"einrühren\"])" "SansSerif" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 5 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5279 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 871 531 "guard b.equals([a,\"abschlagen\"])" "SansSerif" 0 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator 102 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5281 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 429 818 "guard b.equals([a,\"aufkochen\"])" "SansSerif" 0 12 0 REF 219 
            CH.ifa.draw.standard.OffsetLocator 12 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5270 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 856 253 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator 8 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5269 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 698 225 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 328 
            CH.ifa.draw.standard.OffsetLocator -5 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5274 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 547 251 "guard b.equals([a,\"aufschneiden\"])" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 3 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5268 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 362 246 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator -24 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5271 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1072 247 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 371 
            CH.ifa.draw.standard.OffsetLocator 2 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5272 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1307 256 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 400 
            CH.ifa.draw.standard.OffsetLocator 3 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5273 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1513 246 "guard b.equals([a,\"trennen\"])" "SansSerif" 0 12 0 REF 144 
            CH.ifa.draw.standard.OffsetLocator -2 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5284 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 655 1160 "guard b.equals([a,\"auffüllen\"])" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 102 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5283 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 495 1056 "guard b.equals([a,\"abfüllen\"])" "SansSerif" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator -2 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5266 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 64 617 "[\"K1\",\"trennen\"];\n[\"K1\",\"aufschneiden\"];\n[\"K2\",\"aufkochen\"];\n[\"K2\",\"verrühren\"];\n[\"K4\",\"einrühren\"];\n[\"K3\",\"abschlagen\"];\n[\"K4\",\"abfüllen\"];\n[\"K4\",\"auffüllen\"];\n[\"K1\",\"unterheben\"];\n[\"K2\",\"trennen\"];" "SansSerif" 0 12 0 REF 817 
            CH.ifa.draw.standard.OffsetLocator -21 -92 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -2 105 1456 706 