11 
    de.renew.gui.CPNDrawing 104 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 994 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 93 54 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 995 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 204 56 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 996 2 228 64 531 68 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1030 "FillColor" "Color" 112 219 147 255 530 58 20 20 NULL    
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 997 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 1047 329 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 998 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 645 126 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 999 2 796 199 669 139 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1047 "FillColor" "Color" 112 219 147 255 794 192 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 9   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1001 3 658 142 668 204 795 202 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1002 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 725 172 "f" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -5 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1003 2 113 64 204 64 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1004 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 659 127 ":setAnzahl(z)" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 41 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1005 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 86 303 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1006 2 106 313 162 313 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 29  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1007 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 162 305 24 16 NULL    REF 34 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1008 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 157 328 ":init(x)" "SansSerif" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 2 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1009 2 186 312 261 312 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 34  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1010 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 260 302 20 20 NULL    REF 42 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1011 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 220 305 "x" "SansSerif" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1012 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 91 306 "[]" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1013 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 359 302 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1014 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 323 283 ":getStockwerk(x)" "SansSerif" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 4 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1015 2 280 312 359 310 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1016 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 316 304 "x" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1017 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 112 219 147 255 658 261 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 1018 "MarkingAppearance" "Int" 2 2 682 263 796 206 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1019 "FillColor" "Color" 112 219 147 255 1317 141 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1020 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1315 154 "[];[];[];[];[]" "SansSerif" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 21 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1021 2 1318 151 1256 153 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 67  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1022 "FillColor" "Color" 112 219 147 255 1232 146 24 16 NULL    REF 75 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1023 2 1232 153 1167 153 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1024 "FillColor" "Color" 112 219 147 255 1147 143 20 20 NULL    REF 80 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1025 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1225 168 "p: new person" "SansSerif" 0 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 25 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1026 2 1148 153 1109 152 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 80  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1027 "FillColor" "Color" 112 219 147 255 1085 144 24 16 NULL    REF 88 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1028 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1195 146 "p" "SansSerif" 0 12 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1029 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1124 145 "p" "SansSerif" 0 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 7 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1031 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 535 38 "Stockwerk" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 32 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1032 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1076 173 "p:init(s,w)" "SansSerif" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 9 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1033 2 1095 160 1059 330 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 88  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1034 2 531 71 410 103 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1035 "FillColor" "Color" 112 219 147 255 386 99 24 16 NULL    REF 109 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1036 3 410 107 542 110 540 78 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 109  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1037 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1060 162 "guard s!=w" "SansSerif" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator -1 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1038 2 550 69 1085 150 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 88   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1039 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 802 102 "[s,w]" "SansSerif" 0 12 0 REF 117 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1040 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 455 80 "[s,w]" "SansSerif" 0 12 0 REF 105 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1041 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 303 99 "guard s==w" "SansSerif" 0 12 0 REF 109 
            CH.ifa.draw.standard.OffsetLocator -57 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1042 2 269 303 217 72 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1043 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 425 112 "[s,(int) (Math.random()*6 +1)]" "SansSerif" 0 12 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator 44 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1044 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 240 180 "s" "SansSerif" 0 12 0 REF 130 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1045 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 252 33 "[s,(int) (Math.random()*6 +1) ]" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -30 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1046 2 1085 154 814 201 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 88  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   REF 13 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1048 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 909 188 "anzahl+1" "SansSerif" 0 12 0 REF 144 
            CH.ifa.draw.standard.OffsetLocator -11 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1049 3 812 197 878 152 1085 152 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 88   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1050 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 851 135 "anzahl" "SansSerif" 0 12 0 REF 151 
            CH.ifa.draw.standard.OffsetLocator -77 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1051 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 789 173 "0" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -11 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1052 2 1048 337 951 308 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1053 "FillColor" "Color" 112 219 147 255 927 297 24 16 NULL    REF 165 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1054 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 893 318 ":getPerson(p)" "SansSerif" 0 12 0 REF 165 
            CH.ifa.draw.standard.OffsetLocator -3 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1055 "FillColor" "Color" 112 219 147 255 800 611 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1056 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 774 630 ":putPerson(p)" "SansSerif" 0 12 0 REF 169 
            CH.ifa.draw.standard.OffsetLocator 5 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1057 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 719 227 "anzahl" "SansSerif" 0 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1058 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 534 261 ":getAnzahl(anzahl)" "SansSerif" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator -79 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1059 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1077 258 "p" "SansSerif" 0 12 0 REF 101 
            CH.ifa.draw.standard.OffsetLocator 4 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1060 2 811 611 809 554 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 169  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1061 "FillColor" "Color" 112 219 147 255 799 534 20 20 NULL    REF 186 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1062 2 803 538 658 396 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 186  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1063 "FillColor" "Color" 112 219 147 255 638 380 24 16 NULL    REF 191 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1064 2 662 386 1048 340 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 191  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1065 2 638 385 280 314 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 191  
            CH.ifa.draw.figures.ChopEllipseConnector REF 42   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1066 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 680 370 "p:update(s,w) " "SansSerif" 0 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator 75 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1067 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 715 460 "[p,w]" "SansSerif" 0 12 0 REF 187 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1068 2 800 542 537 473 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 186  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1069 "FillColor" "Color" 112 219 147 255 513 462 24 16 NULL    REF 211 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1070 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 653 500 "[p,w]" "SansSerif" 0 12 0 REF 207 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1071 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 494 445 "guard s==w" "SansSerif" 0 12 0 REF 211 
            CH.ifa.draw.standard.OffsetLocator 7 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1072 3 524 478 524 539 800 544 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 211  
            CH.ifa.draw.figures.ChopEllipseConnector REF 186   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1073 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 488 366 "s" "SansSerif" 0 12 0 REF 196 
            CH.ifa.draw.standard.OffsetLocator 32 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1074 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 809 572 "[p, (int) (Math.random()*6+1)]" "SansSerif" 0 12 0 REF 182 
            CH.ifa.draw.standard.OffsetLocator 94 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1075 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 572 547 "[p, (int) (Math.random()*6+1)]" "SansSerif" 0 12 0 REF 218 
            CH.ifa.draw.standard.OffsetLocator 5 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1076 3 274 321 347 467 513 469 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector REF 211   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1077 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 360 459 "s" "SansSerif" 0 12 0 REF 231 
            CH.ifa.draw.standard.OffsetLocator -30 71 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1078 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 991 315 "p" "SansSerif" 0 12 0 REF 161 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1079 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 679 384 "guard s!=w" "SansSerif" 0 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator 65 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1080 3 807 212 879 465 815 611 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 169   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1082 3 821 611 956 493 809 211 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 169  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1083 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 892 402 "anzahl+1" "SansSerif" 0 12 0 REF 249 
            CH.ifa.draw.standard.OffsetLocator 39 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1084 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 687 196 "z" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -37 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1085 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 810 214 "Anzahl" "SansSerif" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 30 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1086 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1084 327 "Pool Person" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 69 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1087 2 812 208 928 297 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 165   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1088 3 947 297 996 252 814 205 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 165  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1089 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 850 245 "anzahl" "SansSerif" 0 12 0 REF 265 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1090 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 937 233 "anzahl-1" "SansSerif" 0 12 0 REF 269 
            CH.ifa.draw.standard.OffsetLocator 58 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1091 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 851 356 "p" "SansSerif" 0 12 0 REF 192 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1000 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 73 37 "[];[];[];[];[]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 3 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.InhibitorConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1092 2 950 297 1150 159 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  "de.renew.gui.CircleDecoration" 
            CH.ifa.draw.standard.ChopBoxConnector REF 165  
            CH.ifa.draw.figures.ChopEllipseConnector REF 80   
        de.renew.gui.InhibitorConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1093 2 927 297 549 73 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  "de.renew.gui.CircleDecoration" 
            CH.ifa.draw.standard.ChopBoxConnector REF 165  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.InhibitorConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1094 2 664 261 545 76 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  "de.renew.gui.CircleDecoration" 
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.InhibitorConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1095 2 682 266 1148 155 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  "de.renew.gui.CircleDecoration" 
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector REF 80   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1081 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 860 455 "anzahl" "SansSerif" 0 12 0 REF 245 
            CH.ifa.draw.standard.OffsetLocator 37 51 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.InhibitorConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1096 2 658 264 112 67 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  "de.renew.gui.CircleDecoration" 
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.InhibitorConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1097 2 682 266 1318 153 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  "de.renew.gui.CircleDecoration" 
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector REF 67   NULL  1836 181 1602 1201 